### ISSUE TITLE
Test Results on C10+?

### ISSUE THREAD

**Issue by Tongcheng** [ikhlestov/vision_networks#1]
Hello, I wonder if you have test results on C10+ dataset? 

Thanks!

**Comment by ikhlestov** [comment]
Hi!
At this moment C10+/100+ datasets were not tested yet, but I hope to add more tests results during a week or two.

**Comment by ikhlestov** [comment]
@Tongcheng Hi again!
I've receive results for Cifar+ datasets - check updated readme on main page.

**Comment by Tongcheng** [comment]
@ikhlestov  Thanks a lot!
