### ISSUE TITLE
can you provide your trained models?

### ISSUE THREAD

**Issue by tengshaofeng** [ikhlestov/vision_networks#10]
hi, ikhlestov,
 you really do a great job. thanks for your share.
can you provide your trained models?

**Comment by ikhlestov** [comment]
Hi!
Unfortunately they were saved on a production server, to which I do not have access now.

**Comment by tengshaofeng** [comment]
ok, thanks , i just need them for transfer training. now i try to trained it in cifar data myself. thanks again.

**Comment by JunMa11** [comment]
Dear  @tengshaofeng 
I also want the trained models for transfer training.
Would it be possible for you to share your trained models?
looking forward to your reply!

**Comment by AlpacaLLaMa643** [comment]
I also need the trained model to implement transfer learning. Hoping to provide. Thx!

**Comment by tengshaofeng** [comment]
@EdwardMa12593 
@tangyuandanhuang 
I use the pytorch code now ,  you can find densenet in torchvison.models,  they provide the trained model.
