### ISSUE TITLE
SVHN normalization issue

### ISSUE THREAD

**Issue by balodhi** [ikhlestov/vision_networks#11]
normalization process of SVHN images has issues. I have changed it which yields much better results.

elseif normalization_type =='mean_0':
train_n = np.full(((images.shape(0),images.shape(1),images.shape(3)),255.0,dtype-np.float32)
pixel_depth=255.0
images = ((images-train_n)/2)/pixel_depth

**Comment by ikhlestov** [comment]
Hi!
What do you mean with better results? Do such approach provide faster learning/converge and better results or will be run faster?

**Comment by balodhi** [comment]
better results mean that it provides faster convergence and higher accuracy. which the previous normalization technique was unable to achieve.

**Comment by ikhlestov** [comment]
ok
It will be great if you add one more flag to the main script, add this new normalization and provide pull request. Are you ok with this?

**Comment by balodhi** [comment]
Yes i was asking the permission to have a pull request. Let me just make a graph comparison of first 6 epochs of both methods.

**Comment by balodhi** [comment]
![result](https://user-images.githubusercontent.com/11146165/32660260-7ed3445e-c665-11e7-98eb-f63be6837eff.jpg)

**Comment by ikhlestov** [comment]
Hm, so huge difference.
Ok, thank you for your pull request - I will run it during next days and if the results be similar I will merge it.

**Comment by ZhenyF** [comment]
It seems it image is substracted by 255 then divided by 2*255, why this one works better?
I tried the method that the image is only divided by 255 (as the paper). And I got 3.4% error rate. Have you got  the same accuracy if only trained on using the original norm method and only on train dataset(without extra)?

**Comment by illarion-rl** [comment]
Hi ZhenyF! Actually I still not compare normalization methods - so I have no answer for your question. You may try both approaches and tell about the difference
