### ISSUE TITLE
The order of image normalization and augmentation seems to be the same as the original implementation?

### ISSUE THREAD

**Issue by zhaohuihai** [ikhlestov/vision_networks#14]
You mentioned that "For Cifar+ datasets image normalization was performed before augmentation. This may cause a little bit lower results than reported in paper."
However, I check the image preprocessing parts of these two implementations, and I find that both of them apply normalization before augmentation, so there should be other reason for the difference in performance.

**Comment by curiositywan** [comment]
I have the same question. I think the question should be whether the order of image normalization and augmentation matter since I notice some other implementations apply normalization after data augmentation during training. If yes, so which order should be better?

**Comment by ikhlestov** [comment]
Hi all!
Here I try to implement code the same way as it was in original repo, but there still can be some difference. Really I don't know exactly what order of augmentation should be correct and better. It should be tested. Unfortunately, I have very tight schedule now. So, if somebody wants to make such experiment and send a result/updated code with PR - it will be really great!

**Comment by curiositywan** [comment]
I've checked the original repo. There is only one minor difference between yours and the authors'. For the augmentation part, the authors do flipping before translating, as in yours, the order is reverse. That's the only difference regarding data processing.

**Comment by illarion-rl** [comment]
Ok, I will change the order and re-run the experiments, when I'm free.

**Comment by ikhlestov** [comment]
Well, for CIFAR100+ dataset I've get an error 25.62 when previous was 25.87. I don't know did this happen because of another augmentation order or because of another initialization. But at least it didn't become worse. So I'm going to change the order. Thank you for reporting the issue!
