### ISSUE TITLE
Problem regarding the number of features generated at the initial convolution layer

### ISSUE THREAD

**Issue by curiositywan** [ikhlestov/vision_networks#15]
In Densenet paper, it mentions that for non-BC architectures, the number of the output features for the initial conv layer should be 16, and for BC architectures, it's twice as the growth rate. However, in your implementation, the number is always twice as the growth rate.

**Comment by ikhlestov** [comment]
Really I adopted code from initial repo([link to code line](https://github.com/liuzhuang13/DenseNet/blob/master/models/densenet.lua#L15)), where it seems to me features from the initial convolution always generated as `grows_rate*2`. If it's incorrect and may cause problem - please, fix me.
