### ISSUE TITLE
requirements issue

### ISSUE THREAD

**Issue by ghost** [ikhlestov/vision_networks#16]
If I want to use most recent `tensorflow-gpu` (Note it is not `tensorflow`)

then I would `pip install tensorflow-gpu`

And `tensorflow-gpu` requires 

```
enum34>=1.1.6
six>=1.10.0
tensorflow-tensorboard<0.5.0,>=0.4.0rc1
numpy>=1.12.1
wheel>=0.26
protobuf>=3.3.0
werkzeug>=0.11.10
markdown>=2.6.8
html5lib==0.9999999
bleach==1.5.0
...
```

So in the requirement.txt file 

I think it would be better to write

```
protobuf>=3.3.0
numpy>=1.12.1
```

instead of 

```
numpy==1.12.0
protobuf==3.1.0.post1
```

Also, I think it is better to use `>=` instead of `==` in all entries in requirements.txt file 

Otherwise when somebody installed `pip install -r requiremets.txt` Maybe he will install a older version of package

**Comment by ikhlestov** [comment]
Hi!
Thank you for reporting the issue. I've update requirements files, so there are only TensorFlow version now matters.
