### ISSUE TITLE
Shouldn't bottlenecks go in the transition layers ? 

### ISSUE THREAD

**Issue by talolard** [ikhlestov/vision_networks#2]
Hello, 
Thanks for this implementation. I'm trying to follow along and don't understand a fine point. 

In the paper they put the bottlenecks as part of the transition layers, whereas [ you placed the bottlenecks in each internal layer of each block](https://github.com/ikhlestov/vision_networks/blob/master/models/dense_net.py#L222)

![layers](https://cloud.githubusercontent.com/assets/5352830/24897353/4c137e74-1ea1-11e7-92f2-258073ac52d3.png)

I suspect that having them in the transition layers is the correct approach, since the point of the bottleneck is to reduce the size of the accrued feature maps due to concatenation. Within each internal layer we aren't accruing much, and I suspect that having the bottlenecks there actually increases the number of parameters as the size of each feature map is less than 4*growth_rate.

**Comment by ikhlestov** [comment]
Hi @talolard !
Thanks for interesting in DenseNets!
You may note that inside attached picture we have DenseBlock parts that consist of [1x1 conv and 3x3 conv]. As I understood from paper bottleneck layers should be added prior every 3x3 conv, if required. I've followed this part of paper:
<img width="494" alt="screen shot 2017-04-11 at 11 08 06 am" src="https://cloud.githubusercontent.com/assets/9900548/24899152/ea3fcaf2-1ea7-11e7-9b70-7170ac2c3215.png">
and some of already provided source code, like [this](https://github.com/titu1994/DenseNet/blob/master/densenet.py#L184).
So we have bottleneck layers really prior to concatenation(concatenation exist only at DenseBlocks, not at the Transition Layers), but also prior 3x3 conv.
And another 1x1 conv we have at the Transition Layers prior to the average pooling: 
<img width="483" alt="screen shot 2017-04-11 at 11 34 24 am" src="https://cloud.githubusercontent.com/assets/9900548/24899963/ecc032e6-1eaa-11e7-84ae-f45034b821a6.png">

At the end we have 1x1 conv layers as in the DenseBlocks as in TransitionLayers.

Regarding number of parameters - yes, every 1x1 layer increase number of training params. But in case of usage bottleneck layers we divide total number of layers by factor of 2. Say in usual DenseNet we have 40 layers(each 3x3 conv), but in DenseNet-BC we will have only 40/2 = 20 layers(each 1x1 + 3x3 conv). With this approach total numbers of training params will decrease.

**Comment by talolard** [comment]
Thanks for getting back to me on that. 
While your interpertation seems to be right, I ran a quick experiment. 
I used densenet as an encoder/decoder for sentances, replacing pooling with "deconvolutions" in the decoder to auto encode sentences. 
Running with bottlnecks only between blocks reduces parameters by 30% and greatly increases training speed. Attached, my loss graph for training: 
Orange - bottleneck after every layer
Purple - bottleneck between blocks only. 
![losscomp](https://cloud.githubusercontent.com/assets/5352830/25091514/365a2d80-2392-11e7-8de7-5581fcfcd892.png)

**Comment by ikhlestov** [comment]
Hi @talolard again!
Your experiment seems to be quite interesting use case, thank you for reporting.
I think this is not bug regarding implementation, so I will close the issue.
But I also try approach with bottleneck layers only between blocks for my future research, thanks for pointing my attention to it!
