### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by phongnhhn92** [ikhlestov/vision_networks#22]
Hello sir, I am curious on how to use you code with my own dataset ?

**Comment by ikhlestov** [comment]
Hi!
You may:
1. Write your own data provider, similar to some in `data_providers` folder
2. Initialize your own data provider at the `run_dense_net.py` script, [line 135](https://github.com/ikhlestov/vision_networks/blob/master/run_dense_net.py#L135)
