### ISSUE TITLE
Train on images on my desktop

### ISSUE THREAD

**Issue by Dhrumit8596** [ikhlestov/vision_networks#23]
How Can I train this model on the images on my desktop?
![screenshot 28](https://user-images.githubusercontent.com/17471088/35899616-68c02866-0bf3-11e8-8f44-3bbd5f1aceb2.png)
Images in the form as shown in the screenshot.

**Comment by ikhlestov** [comment]
Hi!
Of course you may train this network with your own images. But for this you should create provider for your images. Take a look at the [base_provider.py](https://github.com/ikhlestov/vision_networks/blob/master/data_providers/base_provider.py) and [cifar.py](https://github.com/ikhlestov/vision_networks/blob/master/data_providers/cifar.py)(implementation of the provider for the Cifar datasets).
