### ISSUE TITLE
Why did you remove the max pooling layer after the initial convolution?

### ISSUE THREAD

**Issue by Zhengyu-Li** [ikhlestov/vision_networks#26]
I remember there is a 3*3 max pooling layer after the initial convolution. Why remove it?

**Comment by ikhlestov** [comment]
Hi!
Max pooling layer is used after 7x7 convolution layer only for the ImageNet version. I've implemented cifar/svhn version, where initially only 3x3 convolution is used ([link to the authors code](https://github.com/liuzhuang13/DenseNet/blob/master/models/densenet.lua#L70-L74)).
