### ISSUE TITLE
Pre-trained weights 

### ISSUE THREAD

**Issue by mightyroy** [ikhlestov/vision_networks#28]
Hi Ikhlestov,

Thanks for your Tensorflow version of Densenet! I would like to ask if these models are compatible with any available pre-trained weights file out there?

Thanks!

Roy

**Comment by ikhlestov** [comment]
Hi Roy,

Thank you for your interest. I think that models in general compatible with other pretrained weights. This mean that matrices should have same dimensions. Unfortunately, tensorflow namescopes will be different. For example first block may be called "first_layer" or "first_block" at various networks. So you should add a lot of unreasonable effort to transfer savings from one network to another.
