### ISSUE TITLE
How to normalize image in pre-processing step

### ISSUE THREAD

**Issue by John1231983** [ikhlestov/vision_networks#5]
As I read your notice, I found an interesting thing as "_normalized by mean/std of all images in the dataset(train or test), not by its own only_".

>next I’ve implemented per channel normalization… And networks began works even worse. It was not clear for me why. .... After precise debugging, it becomes apparent that images should be normalized by mean/std of all images in the dataset(train or test), not by its own only.

Given a training dataset, it includes 100 images with size 256x256 (gray image). From your notice, you mean that we will find the mean among all 100 images and std of 100 images and normalize a given based on these value. Is it right? For implementation, it likes

```
mean_all=mean[image1, image2,...image100]
std_all=std[image1, image2,...image100]
image1_normalize=(image1-mean_all)/std_all
image2_normalize=(image2-mean_all)/std_all
...
```

In my opinion, using global mean (mean of all images in the dataset) may sensitive to some images which have high illumination. Instead of this, I think that normalization based on mean/std of the image itself will be better. It likes

```
image1_normalize=(image1-image1.mean())/image1.std()
image2_normalize=(image2-image2.mean())/image2.std()
...

```
Do you try with above case? One thing I want to ask if you use global means, then do you need to recompute global mean for the testing set?

**Comment by ikhlestov** [comment]
Hi @John1231983 
I've try with mean/std generated per image and it went to about 2-3 percent worst results. You may try by your own - just change few lines in data provider.
Regarding recomputing - I've calculate mean and std for full dataset and didn't change it if new images are come.

**Comment by John1231983** [comment]
Thanks, the full dataset means training+testing set. Is it right?
So, you first merge training and testing set as the full dataset, then compute the mean and std from the full dataset. The normalize for each image in each set (training and testing) based on the mean of std. Am I right?

**Comment by ikhlestov** [comment]
Yes, you are right. Maybe this is not best approach - but at leas it's working.
