### ISSUE TITLE
reported error results

### ISSUE THREAD

**Issue by balodhi** [ikhlestov/vision_networks#6]
hello
i have a question regarding the reported test (error) results. is it the mean cross entropy ? or something else. please explain these numbers "6.67(7.00)".

**Comment by ikhlestov** [comment]
No, error mean prediction accuracy.  Percent of how many classes were labeled incorrect. For example if we have 100 images and error 7% - it means that 93 images were classified correct, and 7 images receive another class.

**Comment by balodhi** [comment]
how about the keep_prob in your code? it is set to 0.8. 
doesnt it needs to change to 1 while testing

**Comment by ikhlestov** [comment]
Yes, it should be set to 1.0, so on lines https://github.com/ikhlestov/vision_networks/blob/master/models/dense_net.py#L298-L302 it will be disable, if network in test mode.

**Comment by balodhi** [comment]
yes i can see that but i dont find any line which sets keep_prob=1
self.keep_prob is always 0.8

**Comment by ikhlestov** [comment]
Yes, maybe answer should be a little bit different - keep prob will not be set to 1.0 `tf.cond` will just not apply dropout in case of test mode. It will return unchanged `_input`
