### ISSUE TITLE
SVHN performance

### ISSUE THREAD

**Issue by akappeler** [ikhlestov/vision_networks#7]
Hi,

Thanks for providing the code.
I ran your code with SVHN, but it only worked when I set normalization to "by_chanels". 
(This is more an FYI than an issue)

Best
Armin

**Comment by ikhlestov** [comment]
Hi Armin, thank you for reporting the issue.

Can you clarify a little bit what mean "only worked" with normalization by channels? What will be in other case - code will not run at all or we will get large validation error?
