### ISSUE TITLE
Is there any memory-efficient tensorflow Implementation？

### ISSUE THREAD

**Issue by feynman233** [ikhlestov/vision_networks#8]
Hi, I have found the same problem about the GPU memory，and is there any memory-efficient tensorflow Implementation？
Thanks very much!

**Comment by ikhlestov** [comment]
Hi!
I think there should be some memory-efficient implementations, but I don't know exactly any repo. And in this one no memory efficient implementation and at this moment I don't intend to do this. But you are welcome to send pull request)

**Comment by tengshaofeng** [comment]
hi,@feynman233 
@ikhlestov
dose it mean that it can not train densenet_BC on 224*224 pictures?
my gpu is 12GB, and i try to train on 224*224 images ,set the batchsize to 10, it comes the error 'OOM when allocating tensor with shape[10,224,224,108]'

**Comment by ikhlestov** [comment]
Hi!
It seems so. Unfortunately I have no access to the ImageNet dataset, so I not test the network on it.
